"""create votes table

Revision ID: ca2854d80afd
Revises: 468ad561e646
Create Date: 2026-06-16 23:47:52.508825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2854d80afd'
down_revision: Union[str, None] = '468ad561e646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    
    op.create_table(
        'votes',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['post_id'],
            ['posts.id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    
    pass
    # ### end Alembic commands ###
